# Generated by Django 5.2.8 on 2025-11-14 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree_type', models.CharField(choices=[('FYUGP', 'FYUGP (4-year)'), ('Regular', 'Regular (3-year)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apaar_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('caste', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('student_phone_number', models.CharField(max_length=15)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('class_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_charge', to='office.staff')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.semester')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='fee_receipts/')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('Major', 'Major'), ('Minor 1', 'Minor 1'), ('Minor 2', 'Minor 2'), ('VAC 1', 'VAC 1'), ('DSE / VAC 2', 'DSE / VAC 2'), ('SEC', 'SEC'), ('MDC', 'MDC'), ('AEC English', 'AEC English'), ('AEC Other', 'AEC Other')], max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.semester')),
            ],
        ),
    ]
